/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cache/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete cached provider observations (never user-authored rows).
         * @description Delete cached provider observations (never user-authored rows).
         */
        post: operations["cache_clear_api_v1_cache_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cache/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show cache size on disk, entry count and oldest entry age.
         * @description Show cache size on disk, entry count and oldest entry age.
         */
        post: operations["cache_info_api_v1_cache_info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Commands */
        get: operations["commands_api_v1_commands_get"];
        put?: never;
        /**
         * List every registered command with its parameters.
         * @description List every registered command with its parameters.
         */
        post: operations["commands_api_v1_commands_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Print the config file location.
         * @description Print the config file location.
         */
        post: operations["config_path_api_v1_config_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Persist a setting to the config file (mode 0600).
         * @description Persist a setting to the config file (mode 0600).
         */
        post: operations["config_set_api_v1_config_set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show every setting, its value (secrets masked) and source.
         * @description Show every setting, its value (secrets masked) and source.
         */
        post: operations["config_show_api_v1_config_show_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/unset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove a setting from the config file.
         * @description Remove a setting from the config file.
         */
        post: operations["config_unset_api_v1_config_unset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/factors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and cache Fama-French factor returns from the Ken French Data Library.
         * @description Fetch and cache Fama-French factor returns from the Ken French Data Library.
         */
        post: operations["data_factors_api_v1_data_factors_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/fx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and cache daily exchange rates (ECB reference rates, keyless).
         * @description Fetch and cache daily exchange rates (ECB reference rates, keyless).
         */
        post: operations["data_fx_api_v1_data_fx_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/macro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and cache FRED macro series (needs a free FRED API key).
         * @description Fetch and cache FRED macro series (needs a free FRED API key).
         */
        post: operations["data_macro_api_v1_data_macro_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/data/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch and cache daily prices for one or more tickers.
         * @description Fetch and cache daily prices for one or more tickers.
         */
        post: operations["data_prices_api_v1_data_prices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a consistent copy of the database (safe while in use).
         * @description Write a consistent copy of the database (safe while in use).
         */
        post: operations["db_export_api_v1_db_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Database path, schema version, size and per-table row counts.
         * @description Database path, schema version, size and per-table row counts.
         */
        post: operations["db_info_api_v1_db_info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/db/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recover what can be read from a damaged database into a new file; the original is untouched.
         * @description Recover what can be read from a damaged database into a new file; the original is untouched.
         */
        post: operations["db_repair_api_v1_db_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose the install; every failing line says how to fix it.
         * @description Diagnose the install; every failing line says how to fix it.
         */
        post: operations["doctor_api_v1_doctor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Guided setup of every setting; ends by running doctor.
         * @description Guided setup of every setting; ends by running doctor.
         */
        post: operations["init_api_v1_init_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs List */
        get: operations["jobs_list_api_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Get */
        get: operations["job_get_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Job Cancel */
        post: operations["job_cancel_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Events */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/open": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the server if needed and open the browser to a view.
         * @description Start the server if needed and open the browser to a view.
         */
        post: operations["open_api_v1_open_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Walk-forward test: re-solve at each rebalance on prior data only, versus equal weight.
         * @description Walk-forward test: re-solve at each rebalance on prior data only, versus equal weight.
         */
        post: operations["optimize_backtest_api_v1_optimize_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The efficient frontier: one row per portfolio from min variance to max return.
         * @description The efficient frontier: one row per portfolio from min variance to max return.
         */
        post: operations["optimize_frontier_api_v1_optimize_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/markowitz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimal weights for one objective, with the risk/return profile that produced them.
         * @description Optimal weights for one objective, with the risk/return profile that produced them.
         */
        post: operations["optimize_markowitz_api_v1_optimize_markowitz_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/optimize/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * The full risk panel for a fixed-weight portfolio.
         * @description The full risk panel for a fixed-weight portfolio.
         */
        post: operations["optimize_risk_api_v1_optimize_risk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a saved portfolio.
         * @description Delete a saved portfolio.
         */
        post: operations["portfolio_delete_api_v1_portfolio_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List saved portfolios.
         * @description List saved portfolios.
         */
        post: operations["portfolio_list_api_v1_portfolio_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save a named portfolio (tickers, optionally weights).
         * @description Save a named portfolio (tickers, optionally weights).
         */
        post: operations["portfolio_save_api_v1_portfolio_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolio/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show a saved portfolio's holdings.
         * @description Show a saved portfolio's holdings.
         */
        post: operations["portfolio_show_api_v1_portfolio_show_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a recorded run.
         * @description Delete a recorded run.
         */
        post: operations["run_delete_api_v1_run_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare two runs of the same command side by side.
         * @description Compare two runs of the same command side by side.
         */
        post: operations["run_diff_api_v1_run_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List recorded runs, newest first.
         * @description List recorded runs, newest first.
         */
        post: operations["run_list_api_v1_run_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/run/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show one recorded run in full.
         * @description Show one recorded run in full.
         */
        post: operations["run_show_api_v1_run_show_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/serve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the web UI and API (loopback by default).
         * @description Run the web UI and API (loopback by default).
         */
        post: operations["serve_api_v1_serve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/serve/token/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the deployment token; every existing session stops working.
         * @description Replace the deployment token; every existing session stops working.
         */
        post: operations["serve_token_rotate_api_v1_serve_token_rotate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Settings List */
        get: operations["settings_list_api_v1_settings_get"];
        /** Settings Put */
        put: operations["settings_put_api_v1_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{key}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settings Verify */
        post: operations["settings_verify_api_v1_settings__key__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/upgrade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upgrade sobres with the installer that installed it.
         * @description Upgrade sobres with the installer that installed it.
         */
        post: operations["upgrade_api_v1_upgrade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add symbols to a watchlist, creating it if absent; duplicates are no-ops.
         * @description Add symbols to a watchlist, creating it if absent; duplicates are no-ops.
         */
        post: operations["watchlist_add_api_v1_watchlist_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a watchlist.
         * @description Delete a watchlist.
         */
        post: operations["watchlist_delete_api_v1_watchlist_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * List watchlists.
         * @description List watchlists.
         */
        post: operations["watchlist_list_api_v1_watchlist_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Remove symbols from a watchlist.
         * @description Remove symbols from a watchlist.
         */
        post: operations["watchlist_remove_api_v1_watchlist_remove_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/watchlist/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Show a watchlist's symbols.
         * @description Show a watchlist's symbols.
         */
        post: operations["watchlist_show_api_v1_watchlist_show_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BacktestParams */
        BacktestParams: {
            /**
             * Allow Short
             * @description Relax the lower bound from 0 to -1.
             * @default false
             */
            allow_short: boolean;
            /**
             * Base
             * @description Base currency for a multi-currency universe (e.g. USD).
             */
            base?: string | null;
            /**
             * Cost Bps
             * @description One-way transaction cost in basis points.
             * @default 10
             */
            cost_bps: number;
            /**
             * Covariance
             * @description Covariance estimator; Ledoit-Wolf shrinkage by default.
             * @default ledoit_wolf
             * @enum {string}
             */
            covariance: "sample" | "ledoit_wolf" | "ewma" | "semicovariance";
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Fill
             * @description Provider-gap policy: drop, ffill or raise. No default.
             * @enum {string}
             */
            fill: "drop" | "ffill" | "raise";
            /**
             * Lookback
             * @description Estimation window: Nm months, Ny years or N observations.
             * @default 36m
             */
            lookback: string;
            /**
             * Max Weight
             * @description Cap on any single weight.
             */
            max_weight?: number | null;
            /**
             * Objective
             * @description Objective re-solved at each rebalance.
             * @default max_sharpe
             * @enum {string}
             */
            objective: "min_variance" | "max_sharpe" | "target_return" | "target_risk" | "risk_parity" | "equal_weight";
            /**
             * Portfolio
             * @description A saved portfolio's name in place of --tickers.
             */
            portfolio?: string | null;
            /**
             * Rebalance
             * @description Rebalance schedule.
             * @default quarterly
             * @enum {string}
             */
            rebalance: "monthly" | "quarterly" | "annual" | "never";
            /**
             * Returns Estimator
             * @description Expected-return estimator.
             * @default mean_historical
             * @enum {string}
             */
            returns_estimator: "mean_historical" | "ewma" | "capm";
            /**
             * Risk Free
             * @description Annual decimal risk-free rate; default: FRED 3-month bill, or 0.0 without a key.
             */
            risk_free?: number | null;
            /**
             * Save Run
             * @description Record this run in the run history.
             * @default false
             */
            save_run: boolean;
            /**
             * Seed
             * @description Seed for the max-Sharpe random restarts.
             * @default 0
             */
            seed: number;
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
            /**
             * Tickers
             * @description Ticker symbols, e.g. AAPL MSFT NESN.SW (or use --portfolio).
             */
            tickers?: string[] | null;
        };
        /** CacheClearParams */
        CacheClearParams: {
            /**
             * Provider
             * @description Only clear one provider's observations.
             */
            provider?: string | null;
            /**
             * Yes
             * @description Skip the confirmation prompt.
             * @default false
             */
            yes: boolean;
        };
        /** CacheInfoParams */
        CacheInfoParams: Record<string, never>;
        /** CommandsParams */
        CommandsParams: Record<string, never>;
        /** ConfigPathParams */
        ConfigPathParams: Record<string, never>;
        /** ConfigSetParams */
        ConfigSetParams: {
            /**
             * Key
             * @description Setting key, e.g. fred_api_key.
             */
            key: string;
            /**
             * Value
             * @description Value to store.
             */
            value: string;
        };
        /** ConfigShowParams */
        ConfigShowParams: Record<string, never>;
        /** ConfigUnsetParams */
        ConfigUnsetParams: {
            /**
             * Key
             * @description Setting key to remove from the config file.
             */
            key: string;
        };
        /** DbExportParams */
        DbExportParams: {
            /**
             * To
             * Format: path
             * @description Destination file for the consistent copy.
             */
            to: string;
        };
        /** DbInfoParams */
        DbInfoParams: Record<string, never>;
        /** DbRepairParams */
        DbRepairParams: {
            /**
             * To
             * @description Recovery file (default: <db>.recovered).
             */
            to?: string | null;
        };
        /** DoctorParams */
        DoctorParams: {
            /**
             * Fix
             * @description Apply every safe registered repair; never touches secrets.
             * @default false
             */
            fix: boolean;
            /**
             * Offline
             * @description Skip network-dependent checks (reported as skipped).
             * @default false
             */
            offline: boolean;
            /**
             * Strict
             * @description Exit 1 on warnings as well as failures.
             * @default false
             */
            strict: boolean;
        };
        /** FactorsParams */
        FactorsParams: {
            /**
             * End
             * @description Last date (default: latest).
             */
            end?: string | null;
            /**
             * Frequency
             * @description Observation frequency.
             * @default monthly
             * @enum {string}
             */
            frequency: "daily" | "monthly";
            /**
             * Model
             * @description Factor model.
             * @default ff5
             * @enum {string}
             */
            model: "ff3" | "ff5" | "ff5+mom";
            /**
             * Start
             * @description First date (default: full history).
             */
            start?: string | null;
        };
        /** FrontierParams */
        FrontierParams: {
            /**
             * Allow Short
             * @description Relax the lower bound from 0 to -1.
             * @default false
             */
            allow_short: boolean;
            /**
             * Base
             * @description Base currency for a multi-currency universe (e.g. USD).
             */
            base?: string | null;
            /**
             * Covariance
             * @description Covariance estimator; Ledoit-Wolf shrinkage by default.
             * @default ledoit_wolf
             * @enum {string}
             */
            covariance: "sample" | "ledoit_wolf" | "ewma" | "semicovariance";
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Fill
             * @description Provider-gap policy: drop, ffill or raise. No default.
             * @enum {string}
             */
            fill: "drop" | "ffill" | "raise";
            /**
             * Max Weight
             * @description Cap on any single weight.
             */
            max_weight?: number | null;
            /**
             * Points
             * @description Number of frontier points.
             * @default 50
             */
            points: number;
            /**
             * Portfolio
             * @description A saved portfolio's name in place of --tickers.
             */
            portfolio?: string | null;
            /**
             * Returns Estimator
             * @description Expected-return estimator.
             * @default mean_historical
             * @enum {string}
             */
            returns_estimator: "mean_historical" | "ewma" | "capm";
            /**
             * Risk Free
             * @description Annual decimal risk-free rate; default: FRED 3-month bill, or 0.0 without a key.
             */
            risk_free?: number | null;
            /**
             * Save Run
             * @description Record this run in the run history.
             * @default false
             */
            save_run: boolean;
            /**
             * Seed
             * @description Seed for the max-Sharpe random restarts.
             * @default 0
             */
            seed: number;
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
            /**
             * Tickers
             * @description Ticker symbols, e.g. AAPL MSFT NESN.SW (or use --portfolio).
             */
            tickers?: string[] | null;
        };
        /** FxParams */
        FxParams: {
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Pairs
             * @description Currency pairs as EURUSD or EUR/USD: units of quote per one base.
             */
            pairs: string[];
            /**
             * Source
             * @description Rate source.
             * @default ecb
             * @constant
             */
            source: "ecb";
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InitParams */
        InitParams: {
            /**
             * Non Interactive
             * @description Take values from flags and the environment only; never prompt.
             * @default false
             */
            non_interactive: boolean;
            /**
             * Offline
             * @description Skip network checks in the closing doctor run.
             * @default false
             */
            offline: boolean;
            /**
             * Set
             * @description key=value pairs to apply without prompting, e.g. --set fred_api_key=ABC.
             */
            set?: string[];
            /**
             * Verify
             * @description Offer to verify keys with one live request (--no-verify to skip).
             * @default true
             */
            verify: boolean;
            /**
             * Web
             * @description Open the settings page in the browser instead (sobres open settings).
             * @default false
             */
            web: boolean;
        };
        /** LoginBody */
        LoginBody: {
            /** Token */
            token: string;
        };
        /** MacroParams */
        MacroParams: {
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Series
             * @description FRED series ids, e.g. DGS10 CPIAUCSL.
             */
            series: string[];
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
        };
        /** MarkowitzParams */
        MarkowitzParams: {
            /**
             * Allow Short
             * @description Relax the lower bound from 0 to -1.
             * @default false
             */
            allow_short: boolean;
            /**
             * Base
             * @description Base currency for a multi-currency universe (e.g. USD).
             */
            base?: string | null;
            /**
             * Covariance
             * @description Covariance estimator; Ledoit-Wolf shrinkage by default.
             * @default ledoit_wolf
             * @enum {string}
             */
            covariance: "sample" | "ledoit_wolf" | "ewma" | "semicovariance";
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Fill
             * @description Provider-gap policy: drop, ffill or raise. No default.
             * @enum {string}
             */
            fill: "drop" | "ffill" | "raise";
            /**
             * Max Weight
             * @description Cap on any single weight.
             */
            max_weight?: number | null;
            /**
             * Objective
             * @description Optimization objective.
             * @default max_sharpe
             * @enum {string}
             */
            objective: "min_variance" | "max_sharpe" | "target_return" | "target_risk" | "risk_parity" | "equal_weight";
            /**
             * Portfolio
             * @description A saved portfolio's name in place of --tickers.
             */
            portfolio?: string | null;
            /**
             * Returns Estimator
             * @description Expected-return estimator.
             * @default mean_historical
             * @enum {string}
             */
            returns_estimator: "mean_historical" | "ewma" | "capm";
            /**
             * Risk Free
             * @description Annual decimal risk-free rate; default: FRED 3-month bill, or 0.0 without a key.
             */
            risk_free?: number | null;
            /**
             * Save Run
             * @description Record this run in the run history.
             * @default false
             */
            save_run: boolean;
            /**
             * Seed
             * @description Seed for the max-Sharpe random restarts (printed for reproducibility).
             * @default 0
             */
            seed: number;
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
            /**
             * Target
             * @description Target return or risk for target_* objectives.
             */
            target?: number | null;
            /**
             * Tickers
             * @description Ticker symbols, e.g. AAPL MSFT NESN.SW (or use --portfolio).
             */
            tickers?: string[] | null;
        };
        /** OpenParams */
        OpenParams: {
            /**
             * Port
             * @description Port to use or start on.
             * @default 8787
             */
            port: number;
            /**
             * Print Url
             * @description Print the URL instead of launching a browser.
             * @default false
             */
            print_url: boolean;
            /**
             * Target
             * @description View to open: settings, doctor, runs, run <id>, portfolio <name>, or a command name.
             */
            target?: string[];
        };
        /** PortfolioDeleteParams */
        PortfolioDeleteParams: {
            /**
             * Name
             * @description Portfolio name.
             */
            name: string;
            /**
             * Yes
             * @description Skip the confirmation prompt.
             * @default false
             */
            yes: boolean;
        };
        /** PortfolioListParams */
        PortfolioListParams: Record<string, never>;
        /** PortfolioSaveParams */
        PortfolioSaveParams: {
            /**
             * Force
             * @description Replace an existing portfolio of this name.
             * @default false
             */
            force: boolean;
            /**
             * Name
             * @description Portfolio name, e.g. core.
             */
            name: string;
            /**
             * Tickers
             * @description Ticker symbols.
             */
            tickers: string[];
            /**
             * Weights
             * @description Optional weights, one per ticker, summing to 1.
             */
            weights?: number[];
        };
        /** PortfolioShowParams */
        PortfolioShowParams: {
            /**
             * Name
             * @description Portfolio name.
             */
            name: string;
        };
        /** PricesParams */
        PricesParams: {
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Field
             * @description Price field; adj_close is split- and dividend-adjusted (total return).
             * @default adj_close
             * @enum {string}
             */
            field: "adj_close" | "close" | "open" | "high" | "low" | "volume";
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
            /**
             * Tickers
             * @description Ticker symbols, e.g. AAPL MSFT NESN.SW.
             */
            tickers: string[];
        };
        /** RiskParams */
        RiskParams: {
            /**
             * Base
             * @description Base currency for a multi-currency universe (e.g. USD).
             */
            base?: string | null;
            /**
             * End
             * @description Last date (default: today).
             */
            end?: string | null;
            /**
             * Fill
             * @description Provider-gap policy: drop, ffill or raise. No default.
             * @enum {string}
             */
            fill: "drop" | "ffill" | "raise";
            /**
             * Portfolio
             * @description A saved portfolio's name in place of --tickers.
             */
            portfolio?: string | null;
            /**
             * Risk Free
             * @description Annual decimal risk-free rate; default: FRED 3-month bill, or 0.0 without a key.
             */
            risk_free?: number | null;
            /**
             * Save Run
             * @description Record this run in the run history.
             * @default false
             */
            save_run: boolean;
            /**
             * Start
             * Format: date
             * @description First date, YYYY-MM-DD.
             */
            start: string;
            /**
             * Tickers
             * @description Ticker symbols, e.g. AAPL MSFT NESN.SW (or use --portfolio).
             */
            tickers?: string[] | null;
            /**
             * Weights
             * @description Portfolio weights, one per ticker, summing to 1 (from --portfolio if saved).
             */
            weights?: number[];
        };
        /** RunDeleteParams */
        RunDeleteParams: {
            /**
             * Id
             * @description Run id.
             */
            id: string;
            /**
             * Yes
             * @description Skip the confirmation prompt.
             * @default false
             */
            yes: boolean;
        };
        /** RunDiffParams */
        RunDiffParams: {
            /**
             * A
             * @description First run id.
             */
            a: string;
            /**
             * B
             * @description Second run id.
             */
            b: string;
        };
        /** RunListParams */
        RunListParams: {
            /**
             * Command
             * @description Only runs of this command.
             */
            command?: string | null;
            /**
             * Limit
             * @description How many runs to show.
             * @default 20
             */
            limit: number;
        };
        /** RunShowParams */
        RunShowParams: {
            /**
             * Id
             * @description Run id (see `sobres run list`).
             */
            id: string;
        };
        /** ServeParams */
        ServeParams: {
            /**
             * Host
             * @description Bind address; non-loopback needs a token.
             * @default 127.0.0.1
             */
            host: string;
            /**
             * Open
             * @description Open the browser once healthy.
             * @default false
             */
            open: boolean;
            /**
             * Port
             * @description Port.
             * @default 8787
             */
            port: number;
        };
        /** SettingBody */
        SettingBody: {
            /** Key */
            key: string;
            /** Value */
            value: string;
        };
        /** TokenRotateParams */
        TokenRotateParams: {
            /**
             * Token
             * @description Use this token instead of a generated one (must be strong).
             */
            token?: string | null;
        };
        /** UpgradeParams */
        UpgradeParams: {
            /**
             * Check
             * @description Only report whether a newer version exists.
             * @default false
             */
            check: boolean;
            /**
             * Yes
             * @description Skip the confirmation prompt.
             * @default false
             */
            yes: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerifyBody */
        VerifyBody: {
            /** Value */
            value?: string | null;
        };
        /** WatchlistAddParams */
        WatchlistAddParams: {
            /**
             * Name
             * @description Watchlist name, e.g. tech.
             */
            name: string;
            /**
             * Symbols
             * @description Symbols to add.
             */
            symbols: string[];
        };
        /** WatchlistDeleteParams */
        WatchlistDeleteParams: {
            /**
             * Name
             * @description Watchlist name.
             */
            name: string;
            /**
             * Yes
             * @description Skip the confirmation prompt.
             * @default false
             */
            yes: boolean;
        };
        /** WatchlistListParams */
        WatchlistListParams: Record<string, never>;
        /** WatchlistRemoveParams */
        WatchlistRemoveParams: {
            /**
             * Name
             * @description Watchlist name.
             */
            name: string;
            /**
             * Symbols
             * @description Symbols to remove.
             */
            symbols: string[];
        };
        /** WatchlistShowParams */
        WatchlistShowParams: {
            /**
             * Name
             * @description Watchlist name.
             */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cache_clear_api_v1_cache_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CacheClearParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_info_api_v1_cache_info_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CacheInfoParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commands_api_v1_commands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    commands_api_v1_commands_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommandsParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_path_api_v1_config_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigPathParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_set_api_v1_config_set_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigSetParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_show_api_v1_config_show_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigShowParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_unset_api_v1_config_unset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUnsetParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_factors_api_v1_data_factors_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactorsParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_fx_api_v1_data_fx_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FxParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_macro_api_v1_data_macro_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MacroParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    data_prices_api_v1_data_prices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PricesParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    db_export_api_v1_db_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DbExportParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    db_info_api_v1_db_info_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DbInfoParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    db_repair_api_v1_db_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DbRepairParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    doctor_api_v1_doctor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoctorParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    init_api_v1_init_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jobs_list_api_v1_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
                state_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_get_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_cancel_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_api_v1_open_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_backtest_api_v1_optimize_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_frontier_api_v1_optimize_frontier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FrontierParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_markowitz_api_v1_optimize_markowitz_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkowitzParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_risk_api_v1_optimize_risk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_delete_api_v1_portfolio_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioDeleteParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_list_api_v1_portfolio_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioListParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_save_api_v1_portfolio_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioSaveParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_show_api_v1_portfolio_show_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioShowParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_delete_api_v1_run_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunDeleteParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_diff_api_v1_run_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunDiffParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_list_api_v1_run_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunListParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_show_api_v1_run_show_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunShowParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_api_v1_serve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServeParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_token_rotate_api_v1_serve_token_rotate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRotateParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_list_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    settings_put_api_v1_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    settings_verify_api_v1_settings__key__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upgrade_api_v1_upgrade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpgradeParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_add_api_v1_watchlist_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistAddParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_delete_api_v1_watchlist_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistDeleteParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_list_api_v1_watchlist_list_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistListParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_remove_api_v1_watchlist_remove_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistRemoveParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    watchlist_show_api_v1_watchlist_show_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchlistShowParams"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
